enable multiple binaries
rossmacarthur/powerpack pull request #5
Opened 2022-01-14 15:19 UTC by danbi2990

Hi. Thank you for this nice project.
Could you check if this PR is acceptable?
It's for making multiple binaries (e.g. encode & decode) in a single workflow.

2022-01-15 16:58 UTC, rossmacarthur requested changes
Thanks for the contribution 😄, just some minor comments.

2022-01-15 16:58 UTC, rossmacarthur commented on cli/src/main.rs
> +    });
I would prefer a normal `for` loop here and then you can bubble up the io error

```suggestion
    for binary_name in &binary_names {
        let src = target_dir.join(mode.dir()).join(binary_name);
        let dst = workflow_dir.join(binary_name);
        fs::copy(&src, &dst)?;
    }
```

2022-01-15 16:58 UTC, rossmacarthur commented on cli/src/main.rs
> +            binary_names.join(", ")
Perhaps just put whole print in the loop above?

2022-01-17 15:41 UTC, danbi2990 commented
The changes have been applied as you pointed out. Thanks again.

2022-01-18 09:02 UTC, rossmacarthur approved these changes

2022-01-18 09:11 UTC, merged